# Generated by Django 3.2.3 on 2021-05-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=45)),
                ('last_name', models.CharField(max_length=45)),
                ('data_of_birth', models.DateField()),
            ],
            options={
                'db_table': 'actors',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=45)),
                ('release_data', models.DateField()),
                ('running_time', models.IntegerField()),
                ('m2m', models.ManyToManyField(related_name='movie_actor', to='movies.Actor')),
            ],
            options={
                'db_table': 'movies',
            },
        ),
    ]
